name: pull-request

on:
  pull_request:
  workflow_dispatch:

jobs:
  maven-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '11'
          maven-version: '3.8.2'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B install

      - name: Run Sonar analysis
        run: >
          mvn -Psonar
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=tuwien-csd
          -Dsonar.projectKey=tuwien-csd_damap-backend
          -Dsonar.sources=.
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.coverage.exclusions=docker/**/*,
          sonar:sonar
